### ISSUE TITLE
CSS height rule for [type="file"] in FF W7

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern-jquery-ui-theme#227]
Creates an overflow, see the attached image.

**Comment by bloatware** [comment]
![screen shot 2018-12-12 at 21 55 59](https://user-images.githubusercontent.com/11578435/49898505-857e6e00-fe59-11e8-98a3-ddee79e1c88c.png)

**Comment by philwareham** [comment]
Please see: https://github.com/philwareham/textpattern-hive-admin-theme/issues/273 - closing here.
